# Generated by Django 2.2.1 on 2019-06-15 18:27

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('value', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('picture', models.ImageField(upload_to='')),
                ('attachment', models.FileField(upload_to='')),
                ('type', models.ImageField(choices=[(1, 'translate'), (2, 'type'), (3, 'other')], upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(validators=[core.utils.validate_percent])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('revise_date', models.DateTimeField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Contributor')),
                ('sub_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.SubProject')),
            ],
        ),
        migrations.CreateModel(
            name='RequesterProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Requester')),
            ],
        ),
        migrations.CreateModel(
            name='ContributorSubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Contributor')),
                ('sub_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.SubProject')),
            ],
        ),
    ]
