# Generated by Django 2.2.1 on 2019-07-11 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_requesterproject_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subproject',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contributorsubproject',
            name='deadline_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contributorsubproject',
            name='sub_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to='core.SubProject'),
        ),
        migrations.AlterField(
            model_name='project',
            name='value',
            field=models.PositiveIntegerField(),
        ),
    ]
