# Generated by Django 2.2.1 on 2019-07-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190711_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorsubproject',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
