# Generated by Django 2.2.1 on 2019-07-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190711_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='revise_date',
            field=models.DateTimeField(null=True),
        ),
    ]
