# Generated by Django 2.2.1 on 2019-07-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contributorsubproject_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributorsubproject',
            name='attachment',
            field=models.FileField(upload_to=''),
        ),
    ]
