# Generated by Django 2.2.1 on 2019-07-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190713_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributorsubproject',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='revision',
            name='revise_date',
            field=models.DateTimeField(null=True),
        ),
    ]
