# Generated by Django 2.2.1 on 2019-07-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190713_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorsubproject',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
