# Generated by Django 2.2.1 on 2019-08-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_subproject_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
