# Generated by Django 2.2.1 on 2019-08-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_subproject_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
    ]
