# Generated by Django 2.2.1 on 2019-08-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190805_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revision',
        ),
    ]
