# Generated by Django 2.2.1 on 2019-08-05 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator('pdf', 'tex')]),
        ),
    ]
