# Generated by Django 2.2.1 on 2019-08-05 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190805_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'tex'])]),
        ),
    ]
