# Generated by Django 2.2.1 on 2019-08-05 11:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190805_1606'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('admin_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
