# Generated by Django 2.2.1 on 2019-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190805_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
